# Instances
model:
    _target_: model.PointNet
    
    num_classes: ${datamodule.num_classes}
    lr: 1e-3
    weight_decay: 5e-3

datamodule:
    _target_: datamodule.ModelNet40DataModule

    data_dir: ${data_dir}
    batch_size: 64
    num_workers: 4
    num_classes: 40

trainer:
    _target_: pytorch_lightning.Trainer
    gpus: 0
    max_epochs: 10

callbacks:
    model_checkpoint:
        _target_: pytorch_lightning.callbacks.ModelCheckpoint
        monitor: "val/acc"
        mode: "max"
        save_top_k: 3
        save_last: true
        verbose: true
        dirpath: "checkpoints/"
        filename: "epoch={epoch:02d}-val_acc={val/acc:.1f}"
    
    model_summary:
        _target_: pytorch_lightning.callbacks.RichModelSummary
        max_depth: 1
    
    rich_progress_bar:
        _target_: pytorch_lightning.callbacks.RichProgressBar

logger:
    wandb:
        _target_: pytorch_lightning.loggers.wandb.WandbLogger
        project: "pointnet-tests"
        name: ${name}
        save_dir: "."
        log_model: "all"

# other configs
work_dir: ${hydra:runtime.cwd}
data_dir: /home/juil/data/datasets/

seed: null

name: null
