tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger

    save_dir: "./tensorboard"
    name: null
    version: ${name}
    log_graph: false
    default_hp_metric: false
    prefix: ""

